Update MYSQL.sql
The job_id returned by CakeResque.php is a hex string, but it's declared as int in the 'tasks' table, causing it to throw an error 
>Error: [PDOException] SQLSTATE[01000]: Warning: 1265 Data truncated for column 'job_id' at row 1
Request URL: /tasks/setTask
when scheduling tasks.